export const fallbackWorks = [
  {
    id: 'static-portfolio',
    imgLink: 'https://i.imgur.com/WMejxmI.png',
    imgUrl: 'https://i.imgur.com/WMejxmI.png',
    title: '個人網站',
    description: '個人作品集網站，展示前端專案與技術實力。',
    tags: ['React', 'Redux', 'flowbite'],
    gitHubUrl: 'https://github.com/Bruno-Yu/portfolio.git',
    gitPageUrl: 'https://bruno-yu.github.io/portfolio/',
    content: '以 React 為核心框架，Redux 管理狀態，Flowbite 構建 UI 元件；後端以 JSON Server 模擬 API，實現作品資料的 CRUD 管理。',
  },
  {
    id: 'static-resume',
    imgLink: 'https://i.imgur.com/GPCWJOU.png',
    imgUrl: 'https://i.imgur.com/GPCWJOU.png',
    title: '個人履歷網站',
    description: '靜態履歷網站，以 Astro.js 構建，支援暗色模式與多語系切換。',
    tags: ['Astro.js', 'Flowbite', 'Vue', 'i18n'],
    gitHubUrl: 'https://github.com/Bruno-Yu/resume_renew.git',
    gitPageUrl: 'https://bruno-yu.github.io/resume_renew/',
    content: '以 Astro.js 作為網站的核心框架，搭配 Flowbite 建構版面與元件，透過 dark mode 與 i18n 提供更好的使用體驗。',
  },
  {
    id: 'static-nft-gel',
    imgLink: 'https://i.imgur.com/OehaZfu.jpeg',
    imgUrl: 'https://i.imgur.com/OehaZfu.jpeg',
    title: 'NFT GEL',
    description: 'NFT 購物平台靜態實作，ejs 模板渲染、gulp 自動化、Bootstrap5 響應式佈局。',
    tags: ['切版', 'ejs', 'gulp', 'Bootstrap5'],
    gitHubUrl: 'https://github.com/Bruno-Yu/NFT_GEL.git',
    gitPageUrl: 'https://bruno-yu.github.io/NFT_GEL/',
    content: '以 ejs 進行模板渲染，gulp 自動化建置流程，Bootstrap5 實現響應式設計，模擬 NFT 購物平台的前台介面。',
  },
  {
    id: 'static-grandmasam',
    imgLink: 'https://i.imgur.com/OJ9Edmt.jpeg',
    imgUrl: 'https://i.imgur.com/OJ9Edmt.jpeg',
    title: 'GrandMaSam Dine',
    description: '山姆大嬸餐館，前後台分離架構與響應式餐飲網站。',
    tags: ['Vue3', 'Vue_cli', 'Bootstrap5'],
    gitHubUrl: 'https://github.com/Bruno-Yu/GrandMaSam_Diner_renewed.git',
    gitPageUrl: 'https://bruno-yu.github.io/GrandMaSam_Diner_renewed/',
    content: '獨立專案，前後台分離架構，單頁應用（SPA），實現 CRUD 操作、響應式設計與內容管理功能。',
  },
  {
    id: 'static-f2e-2022',
    imgLink: 'https://i.imgur.com/wYioffJ.jpeg',
    imgUrl: 'https://i.imgur.com/wYioffJ.jpeg',
    title: 'THE F2E 2022 黑客松官網重製',
    description: 'THE F2E 2022 黑客松官網重製。',
    tags: ['gulp', 'ejs', 'Tailwind', 'GSAP', 'AOS', 'Lottie'],
    gitHubUrl: 'https://github.com/Bruno-Yu/TheF2E_2022_week1.git',
    gitPageUrl: 'https://bruno-yu.github.io/TheF2E_2022_week1/',
    content: '參與 THE F2E 2022 黑客松挑戰，使用 ejs、gulp、Tailwind 與 GSAP 實作動態網頁效果。',
  },
  {
    id: 'static-dotsign',
    imgLink: 'https://i.imgur.com/jSuGlRX.png',
    imgUrl: 'https://i.imgur.com/jSuGlRX.png',
    title: 'THE F2E 2022 Dotsign',
    description: 'THE F2E 2022 點點簽 PDF 簽名應用程式。',
    tags: ['Vue 3', 'Vue CLI', 'Pinia', 'Tailwind', 'pdf.js', 'fabric.js', 'jspdf.js'],
    gitHubUrl: 'https://github.com/Bruno-Yu/TheF2E_2022_DotSign.git',
    gitPageUrl: 'https://bruno-yu.github.io/TheF2E_2022_DotSign/#/',
    content: '使用 Vue 3、Pinia 進行狀態管理，結合 pdf.js、fabric.js 與 jspdf.js 實現 PDF 文件簽名功能。',
  },
]

export const fallbackSkills = [
  {
    id: 'static-vue',
    title: 'Vue',
    icon: 'price-item-visual',
    details: ['Vue3/Vue2', 'Nuxt3/Nuxt2', 'Vite', 'Pinia/Vuex'],
    order: 0,
  },
  {
    id: 'static-react',
    title: 'React',
    icon: 'price-item-ui',
    details: ['React 18', 'Vite', 'Redux', 'React Query'],
    order: 1,
  },
  {
    id: 'static-layout',
    title: 'Web Layout',
    icon: 'service-item-html&css',
    details: ['CSS/SCSS', 'RWD', 'Tailwind CSS', 'Bootstrap 5', 'Element Plus', 'GSAP'],
    order: 2,
  },
  {
    id: 'static-others',
    title: 'Others',
    icon: 'service-item-front-end',
    details: ['Git', 'Figma', 'Basic unit test', 'Basic Linux', 'Basic SQL'],
    order: 3,
  },
]
